- hosts: all
  become: true
  vars_files: "variables.yml"

  tasks:
  - name: Install nginx web server
    package:
      name: nginx
      state: latest

  - name: Copy proxy conf files
    template:
      src: proxy.conf.j2
      dest: /etc/nginx/conf.d/proxy.conf
      force: yes
    notify:
        - Restart nginx

  handlers:
    - name: Restart nginx
      systemd:
        state: restarted
        name: nginx

