- hosts: all
  become: true


  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Install python3-pip python3-setuptools libev-dev locales
      package:
        name:
          - python3-pip
          - python3-setuptools
          - libev-dev
          - locales
          - python3-venv
          - libc6-dev
          - python3-dev
          - policykit-1

        state: latest

    - name: Install packages with pip3 flask bjoern sqlalchemy sqlalchemy_utils pymysql pytest cryptography
      pip:
        executable: pip3
        #virtualenv: /tmp/py3
        #virtualenv_command: /usr/bin/python3 -m venv
        name:
          - flask
          - bjoern
          - sqlalchemy
          - sqlalchemy_utils
          - pymysql
          - pytest
          - cryptography
        state: latest

    - name: Ensure a locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present

