- hosts: all
  vars_files: "variables.yml"


  tasks:
    - name: install git
      become: true
      package:
        name: git
        state: present

    - name: cone git repo
      git:
        repo: "{{project_repo}}"
        dest: "{{project_path}}"


    - name: add guestbook to the systemd
      template:
        src: "{{templates_path}}/systemd/guestbook.service.j2"
        dest: "/etc/systemd/system/guestbook.service"
        mode: '664'

    - name: enable systemd unit
      systemd:
        name: guestbook
        enabled: true
        state: restarted


    - name: Copy env variables of guestbook

      template:
        src:  "{{templates_path}}/guestbook/config.py.j2"
        dest: "{{project_path}}/guest_book/config.py"
        check_mode: no
      notify:
         - Copy latest proxy conf files
         - Restart guestbook
         - Restart nginx
      tags: update_guestbook_conf



  handlers:
    - name: Copy latest proxy conf files
      template:
        src: "{{templates_path}}/proxy/proxy.conf.j2"
        dest: /etc/nginx/conf.d/proxy.conf

    - name: Restart guestbook
      systemd:
        state: restarted
        name: guestbook

    - name: Restart nginx
      systemd:
        state: restarted
        daemon_reload: yes
        name: nginx