- hosts: all
  become: true
  vars_files: "variables.yml"

  tasks:
  - name: Install nginx web server
    package:
      name: nginx
      state: latest

  - name: Create project directory
    file:
      path: "{{ project_path }}"
      state: directory

  - na



